export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Roboto',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
        ],
        mono: [
          'Roboto Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
      colors: {
        "inverse-primary": "#b2c5ff",
        "primary-container": "#0056d2",
        "on-secondary-fixed": "#181c20",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#616569",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-low": "#f3f3f4",
        "surface": "#f9f9f9",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dfe3e8",
        "surface-container-high": "#e8e8e8",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "background": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c0c7d6",
        "tertiary-container": "#585f6c",
        "surface-tint": "#0056d2",
        "on-surface-variant": "#424654",
        "surface-container": "#eeeeee",
        "outline": "#737785",
        "on-tertiary-fixed": "#151c27",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#0040a1",
        "on-primary-fixed": "#001847",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-container": "#ccd8ff",
        "tertiary-fixed": "#dce3f2",
        "on-error": "#ffffff",
        "tertiary": "#404754",
        "secondary": "#5b5f63",
        "on-secondary": "#ffffff",
        "primary": "#0040a1",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#d2d9e9",
        "on-tertiary-fixed-variant": "#404754",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f0f1f1",
        "secondary-fixed-dim": "#c3c7cc",
        "secondary-container": "#dfe3e8",
        "outline-variant": "#c3c6d6",
        "on-secondary-fixed-variant": "#43474b"
      },
      spacing: {
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "sidebar-width": "280px",
        "stack-md": "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "stack-lg": "48px",
        "base": "8px",
        "gutter": "24px"
      },
    },
  },
  plugins: [],
}